Merging changes from develop to main
Atabek04/gym-app pull request #3
Opened 2024-09-12 11:22 UTC by Atabek04

2024-09-15 15:00 UTC, MadinaBaizhanova requested changes
Hello, Otabek,

Please review my comments! If you have any questions please let me know!

2024-09-15 16:25 UTC, Atabek04 commented on src/main/java/com/epam/gym/facade/GymFacade.java
>  public class GymFacade {
Actually @maximelyashevich  suggested me that one. Cause some methods are involving multiple database operations that must be executed as a single unit

2024-09-15 16:25 UTC, Atabek04 commented on src/main/java/com/epam/gym/cli/GymCLI.java
> +                case 1:
It will give you another chance here's the method `readInt`:
```java
public static int readInt(Scanner scanner, String prompt) {
        while (true) {
            logger.info(prompt);
            String input = scanner.nextLine();
            try {
                var number = Integer.parseInt(input);
                if (number < 0) {
                    throw new NumberFormatException();
                }
                return number;
            } catch (NumberFormatException e) {
                log.error("Invalid number. Please try again.");
            }
        }
    }
    ```

2024-09-15 16:25 UTC, Atabek04 commented on src/main/java/com/epam/gym/cli/CLIHelper.java
> +        var role = user.getRole().toString().substring(5).toLowerCase();
In my opinion, the number 5 here is logical. Cause my role enum is look like this: ROLE_TRAINER. So in order to take role on entity name itself I need to substring it from 5th index.
In other words Idk what constants should I add...

2024-09-15 16:25 UTC, Atabek04 commented on src/main/java/com/epam/gym/cli/GymCLI.java
> -                if (choice == 13) {
This is a CLI, our temporary UI. In next module I will fix it, by removing all my CLI package ;)

2024-09-15 16:25 UTC, Atabek04 commented on src/main/java/com/epam/gym/cli/GymCLI.java
> +            case 1 -> checkAndExecute(role, () -> traineeCLI.updateTrainee(scanner), UserRole.ROLE_TRAINEE);
default case will be triggered. In our case logger will show some error message and app gives you another attempt.

2024-09-16 08:39 UTC, MadinaBaizhanova approved these changes

2024-09-21 04:40 UTC, merged