merge to main: Switching from Spring to Spring Boot 🚀
Atabek04/gym-app pull request #5
Opened 2024-10-09 01:21 UTC by Atabek04

2024-10-10 19:48 UTC, m-nurbek requested changes
Good job!

Please review my comments.
I will continue to add more comments about your project, since I can see there is a job to be done to improve it. My suggestion are to improve your code style, remove unnecessary configurations in your application and tests. I also have questions about your integration tests that mock something but shouldn't do so. 
Also, I noticed that you only use one application.yml file to configure your spring boot project and I don't see any profiles inside it. You should change your config for different profiles, this can easily be done with just naming your application.yml file properly (e.g. application-dev.yml, application-prod.yml).

Best regards,
Nurbek

2024-10-10 19:48 UTC, m-nurbek commented on src/main/java/com/epam/gym/repository/UserRepository.java
> +    @Modifying
also here

2024-10-10 19:48 UTC, m-nurbek commented on src/main/java/com/epam/gym/service/impl/TraineeServiceImpl.java
>          var createdUser = userService.create(toUser(request))
Where 'toUser' method came from? Consider importing just a Utility class, not concrete methods

```java
UserMapper.toUser(request)
```

2024-10-10 19:48 UTC, m-nurbek commented on src/test/java/com/epam/gym/api/TraineeControllerIntegrationTest.java
>  @ExtendWith({SpringExtension.class, TraineeServiceParameterResolver.class})
Why just not annotate it with SpringBootTest instead of your annotations?

2024-10-10 19:48 UTC, m-nurbek commented on src/test/java/com/epam/gym/api/TraineeControllerIntegrationTest.java
```java
@BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        mockMvc = MockMvcBuilders.standaloneSetup(traineeController)
                .setControllerAdvice(new GlobalExceptionHandler()) // Add global exception handler if needed
                .addFilter(new CharacterEncodingFilter("UTF-8", true)) // Handle character encoding
                .build();
    }
```

You have some useless comments here

2024-10-10 19:48 UTC, m-nurbek commented on src/test/java/com/epam/gym/api/TraineeControllerIntegrationTest.java
```java
@BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        mockMvc = MockMvcBuilders.standaloneSetup(traineeController)
                .setControllerAdvice(new GlobalExceptionHandler()) // Add global exception handler if needed
                .addFilter(new CharacterEncodingFilter("UTF-8", true)) // Handle character encoding
                .build();
    }
```

You have some useless comments here

2024-10-10 19:48 UTC, m-nurbek commented on src/test/java/com/epam/gym/service/TrainingServiceTest.java
>          Long trainingId = 1L;
Its not super necessary but I would like to see the comments like //given, //when, //then. This will help me to see what is given, what is tested, and what is asserted.
Consider adding them to your tests

2024-10-10 19:48 UTC, m-nurbek commented on src/test/java/com/epam/gym/service/TrainingServiceTest.java
>          Long trainingId = 1L;
Its not super necessary but I would like to see the comments like //given, //when, //then. This will help me to see what is given, what is tested, and what is asserted.
Consider adding them to your tests

2024-10-10 19:48 UTC, m-nurbek commented on src/test/java/com/epam/gym/api/TrainerControllerIntegrationTest.java
If this is an IntegrationTest then why are you mocking something?

2024-10-11 09:41 UTC, Atabek04 commented on src/main/java/com/epam/gym/actuator/ExternalServiceHealthIndicator.java
> +    private boolean checkExternalServiceHealth() {
I just left that as a specification or todo for future. I will implement it in Security Model.

2024-10-11 09:56 UTC, Atabek04 commented on src/main/java/com/epam/gym/controller/AuthController.java
>      public ResponseEntity<String> login(@Valid @RequestBody UserCredentials credentials) {
I prefer leaving my old version of code for now. Cause as I understand it just removes `return ResponseEntity` part, and make your code look cleaner. Surely I will use that best practice in my future controllers.

2024-10-11 12:10 UTC, Atabek04 commented on src/main/java/com/epam/gym/service/impl/TraineeServiceImpl.java
>          var createdUser = userService.create(toUser(request))
I understand that there might be a little bit context loss. But static import makes my code more readable and help to avoid multiple repetition, cause I used `toUser()` a lot. But I got you.

I will consider using fully qualified method call, when the context isn't obvious.

2024-10-11 12:18 UTC, Atabek04 commented on src/test/java/com/epam/gym/api/TraineeControllerIntegrationTest.java
>  @ExtendWith({SpringExtension.class, TraineeServiceParameterResolver.class})
Cause if I'm not mistaken `@SpringBootTest` is used to load the full application context. And in your application you should choose which profile to use (for example 'test'). But in my case I have separate test profile in test package, that's why I'm using `@ActiveProfiles("test")` at the same time.

I will fix it when I'll add rest of the profiles

2024-10-11 14:46 UTC, Atabek04 commented on src/test/java/com/epam/gym/api/TrainerControllerIntegrationTest.java
yes, you're right. I totally forget about that.

2024-10-11 16:43 UTC, maximelyashevich approved these changes
Good job! Reviewed from my side.

2024-10-11 16:43 UTC, maximelyashevich commented on pom.xml
>                  <version>3.10.1</version>
Please extract to Maven properties.

2024-10-11 16:43 UTC, maximelyashevich commented on pom.xml
> +                <version>3.2.5</version>
Please extract to Maven properties.

2024-10-11 16:43 UTC, maximelyashevich commented on src/main/java/com/epam/gym/GymApp.java
> +@EnableWebMvc
What is the reason to use this annotation? Won't `@SpringBootApplication` cover web-related logic?

2024-10-11 16:43 UTC, maximelyashevich commented on src/main/java/com/epam/gym/actuator/DiskSpaceHealthIndicator.java
> +    private static final long THRESHOLD = 100 * 1024 * 1024;  // 100 MB threshold
```suggestion
    private static final long THRESHOLD = 100L * 1024L * 1024L;  // 100 MB threshold
```

2024-10-11 16:43 UTC, maximelyashevich commented on src/main/java/com/epam/gym/actuator/DiskSpaceHealthIndicator.java
> +        }
Duplicated String, please extract to the constant.

2024-10-11 16:43 UTC, maximelyashevich commented on src/main/java/com/epam/gym/actuator/ExternalServiceHealthIndicator.java
> +        }
Let's rename `serviceUp` to `isServiceUp` to increade code readability:
```suggestion
        boolean isServiceUp = checkExternalServiceHealth();

        if (isServiceUp) {
            return Health.up().withDetail("External Service", "Available").build();
        } else {
            return Health.down().withDetail("External Service", "Not Available").build();
        }
```

Please introduce String constants for duplicated String literals.

2024-10-11 16:43 UTC, maximelyashevich commented on src/main/java/com/epam/gym/controller/AuthController.java
>          log.info("Login attempt for user: {}", credentials.username());
I think debug level is more appropriate here:
```suggestion
        log.debug("Login attempt for user: {}", credentials.username());
```

2024-10-11 16:43 UTC, maximelyashevich commented on src/main/java/com/epam/gym/controller/AuthController.java
>      public ResponseEntity<String> login(@Valid @RequestBody UserCredentials credentials) {
I suggest considering:
1. `@ResponseStatus()` annotation to declaratively define status code.
2. Eliminate the use of `ResponseEntity` and keep only your wrapped type.
3. Delegate business logic to service layer like throwing an exception in case of unauthenticated action that later will be processed by your exception handler.
4. Please be aware that HTTP 200 OK is the default status code, thus, no need to declare it explicitly.

After code refactoring, your controller method may look like this:
```Java
@PostMapping("/login")
public void login(@Valid @RequestBody UserCredentials credentials) {
     userService.tryToAuthenticate(credentials);
}
```

Please apply the similar refactoring for all your controllers.

2024-10-11 16:43 UTC, maximelyashevich commented on src/main/java/com/epam/gym/util/UpdateEntityFields.java
> +    }
Please format your code.

2024-10-11 16:43 UTC, maximelyashevich commented on src/test/java/com/epam/gym/api/TrainerControllerIntegrationTest.java
>  @ExtendWith({SpringExtension.class, TrainerServiceParameterResolver.class})
Can we consider `@SpringBootTest` for this class?

2024-10-11 16:43 UTC, maximelyashevich commented on src/main/java/com/epam/gym/dto/UserCredentials.java
> +import lombok.Setter;
Unused imports:
```suggestion
```

2024-10-12 02:53 UTC, merged